services:
  database:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: development
      POSTGRES_DB: development
  adminer:
    image: adminer
    restart: always
    depends_on:
     - database
    ports:
     - 8080:8080
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 3000:3000
    depends_on:
      - database
    environment:
      DOCKER: docker
